# Generated by Django 5.1.1 on 2024-09-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
