# Generated by Django 5.1.1 on 2024-09-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_alter_agendamento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='valor_pagamento',
            field=models.IntegerField(),
        ),
    ]
